### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by yubin2020** [yassouali/SCL#1]
Hello! 
When I run this program,there is a UserWarning: Mixed memory format inputs detected while calling the operator. The operator will output contiguous tensor even if some of the inputs are in channels_last format.(function operator()).
How do you solve this warning?
Thanks!

**Comment by yassouali** [comment]
Hi yubin2020, 

Thank you for your intrest in our work.

This is probably due to the permute/view operation where the shapes change by only changing the way they are indexed (meta information) without changing their location, but I don't think this will cause any problems.

If you want to remove this warning, simply add .contigous() after the permute operations in the attention module, and this will fix it.
